### PR TITLE
Setup ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Setup up CI with travis :smiley:

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Mmmmm..
dba7318 -> Metalsmith 2, need es6. Hence not compatible with 0.10 and 0.12

@davidxmoody 
What do you prefer. Keep metalsmith 1, or go for metalsmith 2 and drop outdated node?

**Comment by davidxmoody** [comment]
Hey, thanks very much for the pull request, it's awesome! Also, sorry for the late reply, I've been busy over the last few weeks.

A few points regarding your commits:

- I've not used Travis before but I assume your config is correct. I'll just merge it and see if it works.
- Badges are a good idea.
- Compact docs are a good idea (not sure why I ever had it on two lines anyway).
- As for Metalsmith and Node versions, I'm still using Node 0.12 so I want to support that. You can run Metalsmith 2 in Node 0.12 with the `--harmony` flag anyway. I'll update the test command.

**Comment by davidxmoody** [comment]
Oops, accidentally closed, I'll merge now.

**Comment by AdrieanKhisbe** [comment]
You're welcome @davidxmoody.
No problem, i know what is tit to be busy too :)

**Pull request merged**
